---
title: "Spatiotemporal models of `r paste(params$species)` biomass with RW"
author: "Philina English"
date: "`r Sys.Date()`"
output: html_document
params:
    # species: "Canary Rockfish"
    # species: "Arrowtooth Flounder"
    # species: "Big Skate"
    # species: "North Pacific Spiny Dogfish"
    species: "Pacific Ocean Perch"
    # species: "Bocaccio"
    # species: "Rougheye/Blackspotted Rockfish Complex"
    # species: "Pacific Sand Lance"
    # species: "Pacific Herring"
    # region: "Coast-wide trawl surveys"
    # region: "HBLL outside surveys"
    # region: "HBLL inside surveys"
    region: "WCHG only"
    delta_model: TRUE
    # region: "HBLL inside surveys"
    name: "-rw-no-covs" # covariate string used to name model rds
    # update_model: FALSE
    update_model: TRUE # TRUE will over write past models; will alway attempt a model if none exists
    update_index: TRUE
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(
  fig.width = 11, fig.height = 8.5,
  # fig.path=paste0("figs/", spp, "/"),
  echo = FALSE, warning = FALSE, message = FALSE
)
library(dplyr)
library(ggplot2)
library(gfplot)
library(gfdata)
library(sdmTMB)

# options(scipen = 999)
theme_set(
  gfplot::theme_pbs(base_size = 14)
)

# clean up environment just in case
# rm(data, d, m, m1, m2, p, i, g)
```

```{r params}
species <- params$species
region <- params$region
name <- params$name
delta_model <- params$delta_model
update_model <- params$update_model
update_index <- params$update_index

paste("region =", region)
paste("delta =", delta_model)
paste("model label =", name)
```
Load data
```{r, message=FALSE, warning=FALSE}
spp <- gsub(" ", "-", gsub("\\/", "-", tolower(species)))
anisotropy <- FALSE

if (region == "Both odd year trawl surveys") {
  nd_all <- readRDS(here::here("data-generated/nd_whole_coast_index.rds")) %>% mutate(area = 4)
  survey <- c("SYN QCS", "SYN HS")
  type <- "Synoptic trawl"
  model_ssid <- c(1, 3)
}

if (region == "QCS only") {
  nd_all <- readRDS(here::here("data-generated/nd_whole_coast_index.rds")) %>% mutate(area = 4)
  survey <- c("SYN QCS")
  type <- "Synoptic trawl"
  model_ssid <- c(1)
}

if (region == "HS only") {
  nd_all <- readRDS(here::here("data-generated/nd_whole_coast_index.rds")) %>% mutate(area = 4)
  survey <- c("SYN HS")
  type <- "Synoptic trawl"
  model_ssid <- c(3)
}

if (region == "WCVI only") {
  nd_all <- readRDS(here::here("data-generated/nd_whole_coast_index.rds")) %>% mutate(area = 4)
  survey <- c("SYN WCVI")
  type <- "Synoptic trawl"
  model_ssid <- c(4)
}

if (region == "WCHG only") {
  nd_all <- readRDS(here::here("data-generated/nd_whole_coast_index.rds")) %>% mutate(area = 4)
  survey <- c("SYN WCHG")
  type <- "Synoptic trawl"
  model_ssid <- c(16)
  # anisotropy <- TRUE
}

if (region == "Coast-wide trawl surveys") {
  nd_all <- readRDS(here::here("data-generated/nd_whole_coast_index.rds")) %>% mutate(area = 4)
  survey <- c("SYN QCS", "SYN HS", "SYN WCVI", "SYN WCHG")
  type <- "Synoptic trawl"
  model_ssid <- c(1, 3, 4, 16)
}

if (region == "North (PMFC 5DE)") {
  nd_all <- readRDS(here::here("data-generated/nd_whole_coast_index.rds")) %>% mutate(area = 4)
  nd_5D <- filter(nd_all, survey == "SYN HS") %>% filter(Y > 5907.814)
  nd_5E <- filter(nd_all, survey == "SYN WCHG")
  nd_all <- bind_rows(nd_5D, nd_5E)
  survey <- c("SYN HS", "SYN WCHG")
  type <- "Synoptic trawl"
  model_ssid <- c(3, 16)
}

if (region == "South (PMFC 3CD5ABC)") {
  nd_all <- readRDS(here::here("data-generated/nd_whole_coast_index.rds")) %>% mutate(area = 4)
  nd_5C <- filter(nd_all, survey == "SYN HS") %>% filter(Y < 5907.814)
  nd_south <- filter(nd_all, survey %in% c("SYN QCS", "SYN WCVI"))
  nd_all <- bind_rows(nd_5C, nd_south)
  survey <- c("SYN HS", "SYN QCS", "SYN WCVI")
  type <- "Synoptic trawl"
  model_ssid <- c(1, 3, 4)
}

if (region == "South 5 only (PMFC 5ABC)") {
  nd_all <- readRDS(here::here("data-generated/nd_whole_coast_index.rds")) %>% mutate(area = 4)
  nd_5C <- filter(nd_all, survey == "SYN HS") %>% filter(Y < 5907.814)
  nd_QCS <- filter(nd_all, survey %in% c("SYN QCS"))
  nd_all <- bind_rows(nd_5C, nd_QCS)
  survey <- c("SYN HS", "SYN QCS")
  type <- "Synoptic trawl"
  model_ssid <- c(1, 3)
}

if (region == "HS & WCHG") {
  nd_all <- readRDS(here::here("data-generated/nd_whole_coast_index.rds")) %>% mutate(area = 4)
  survey <- c("SYN HS", "SYN WCHG")
  type <- "Synoptic trawl"
  model_ssid <- c(3, 16)
}

if (region == "QCS & WCVI") {
  nd_all <- readRDS(here::here("data-generated/nd_whole_coast_index.rds")) %>% mutate(area = 4)
  survey <- c("SYN QCS", "SYN WCVI")
  type <- "Synoptic trawl"
  model_ssid <- c(1, 4)
}

if (region == "HBLL outside surveys") {
  nd_all <- readRDS(here::here("data-generated/nd_hbll_outside_index.rds"))
  survey <- c("HBLL OUT N", "HBLL OUT S")
  type <- "HBLL (outside)"
  model_ssid <- c(22, 36)
}

if (region == "HBLL inside surveys") {
  nd_all <- readRDS(here::here("data-generated/nd_hbll_inside_index.rds"))
  survey <- c("HBLL INS N", "HBLL INS S")
  type <- "HBLL (inside)"
  model_ssid <- c(39, 40)
}

if (region != "HBLL inside surveys") {
  all_data <- readRDS(here::here("data-raw/all-survey-sets-2021.rds")) %>%
    filter(species_common_name == tolower(species)) %>%
    rename(survey_series_id = survey_series_id.x)
} else {
  all_data <- readRDS(here::here("data-raw/all-inside-hbll-2021.rds")) %>%
    filter(species_common_name == tolower(species))
}
```


Filter data 
```{r}
if (type == "Synoptic trawl") {
  d <- all_data %>%
    filter(survey_abbrev %in% survey)
  units <- "density_kgpm2"
  d$density <- d[[units]] * 1000000 # change from per m2 to per km2
  family <- tweedie(link = "log") # to be used if not a delta model
} else {
  d <- all_data %>%
    filter(survey_abbrev %in% survey)
  units <- "density_ppkm2"
  d$density <- d[[units]] # change from per m2 to per km2
  family <- tweedie(link = "log")
  # family <- nbinom2(link = 'log') # could use this instead, but would need to change units and add offset
}

if (region == "North (PMFC 5DE)") {
  d <- d %>% filter(survey_abbrev == "SYN WCHG" | latitude > 53.3)
}

if (region == "South (PMFC 3CD5ABC)") {
  d <- d %>% filter(survey_abbrev != "SYN WCHG" & latitude < 53.3)
}

if (region == "South 5 only (PMFC 5ABC)") {
  d <- d %>% filter(survey_abbrev %in% c("SYN QCS", "SYN HS") & latitude < 53.3)
}

positive_sets <- filter(d, density != 0)
prop_pos <- round(nrow(positive_sets) / nrow(d), digits = 3)
data <- d %>% filter(survey_abbrev %in% unique(positive_sets$survey_abbrev))
ssid_string <- paste0(unique(data$survey_series_id), collapse = "n")
surv_string <- paste0(unique(data$survey_abbrev), collapse = ", ")
data <- sdmTMB::add_utm_columns(data, c("longitude", "latitude"), utm_crs = 32609)
```

Make mesh
```{r}
cutoff <- 10
if (region %in% c("WCHG only", "HBLL inside surveys")) {
  cutoff <- 5
}

spde <- make_mesh(data, xy_cols = c("X", "Y"), cutoff = cutoff)

plot(spde)

if (delta_model) {
  data <- data %>% mutate(present = ifelse(density > 0, 1, 0))
  data2 <- dplyr::filter(data, density > 0)
  spde2 <- make_mesh(data2, xy_cols = c("X", "Y"), cutoff = cutoff)
  plot(spde2)
}
```

```{r}
# Check if a model already exists
dir.create(here::here("data-generated/models"), showWarnings = FALSE)
if (delta_model) {
  f <- here::here(paste0("data-generated/models/m-", spp, "-", ssid_string, name, "-gamma.rds"))
  if (file.exists(f)) {
    m2 <- readRDS(f)
  } else {
    update_model <- TRUE
  }
} else {
  f <- readRDS(here::here(paste0("data-generated/models/m-", spp, "-", ssid_string, name, ".rds")))
  if (file.exists(f)) {
    m <- readRDS(f)
  } else {
    update_model <- TRUE
  }
}
```

Run sdmTMB model

```{r}
if (update_model) {
  year_range <- range(data$year)
  all_years <- data.frame(year = year_range[1]:year_range[2])
  missing_years <- anti_join(all_years, data, by = "year") %>%
    select(year) %>%
    unique()
  missing_years <- missing_years$year

  if (delta_model) {
    tictoc::tic()

    m1 <- sdmTMB(
      present ~ 1,
      data,
      mesh = spde,
      time = "year",
      extra_time = missing_years,
      family = binomial(),
      spatial = "on",
      spatiotemporal = "RW",
      anisotropy = anisotropy,
      silent = TRUE
    )
    tictoc::toc()
    saveRDS(m1, file = here::here(paste0("data-generated/models/m-", spp, "-", ssid_string, name, "-presence.rds")))

    if (m1$sd_report$pdHess & !m1$bad_eig) {

      # check if positive sets are found in all years
      if (!all(sort(unique(data$year)) == sort(unique(data2$year)))) {
        pos_years <- data2 %>% select(year)
        missing_years <- anti_join(all_years, data2, by = "year") %>%
          select(year) %>%
          unique()
        missing_years2 <- missing_years$year
      } else {
        missing_years2 <- missing_years
      }

      tictoc::tic()

      m2 <- sdmTMB(
        density ~ 1,
        data2,
        mesh = spde2,
        time = "year",
        extra_time = missing_years2,
        family = Gamma(link = "log"),
        spatial = "on",
        spatiotemporal = "RW",
        anisotropy = anisotropy,
        silent = TRUE
      )
      tictoc::toc()
      saveRDS(m2, file = here::here(paste0("data-generated/models/m-", spp, "-", ssid_string, name, "-gamma.rds")))
    } else {
      delta_model <- FALSE
    }

    if (!m2$sd_report$pdHess | m2$bad_eig) {
      delta_model <- FALSE
    }
  }

  if (!delta_model) {
    tictoc::tic()
    m <- sdmTMB(
      density ~ 1,
      data,
      mesh = spde,
      time = "year",
      extra_time = missing_years,
      family = family,
      spatial = "on",
      spatiotemporal = "RW",
      anisotropy = anisotropy,
      silent = TRUE
    )

    saveRDS(m, file = here::here(paste0("data-generated/models/m-", spp, "-", ssid_string, name, ".rds")))
    tictoc::toc()
  }
}
```

```{r}
# if (delta_model) {
try({
  m1 <- readRDS(here::here(paste0("data-generated/models/m-", spp, "-", ssid_string, name, "-presence.rds")))
  if (max(m1$gradients) > 0.01) {
    m1 <- run_extra_optimization(m1, newton_loops = 1L, nlminb_loops = 0L)
    saveRDS(m1, file = paste0("models/m-", spp, "-", ssid_string, name, "-presence.rds"))
  }
})
try({
  m2 <- readRDS(here::here(paste0("data-generated/models/m-", spp, "-", ssid_string, name, "-gamma.rds")))
  if (max(m2$gradients) > 0.01) {
    m2 <- run_extra_optimization(m2, newton_loops = 1L, nlminb_loops = 0L)
    saveRDS(m2, file = paste0("models/m-", spp, "-", ssid_string, name, "-presence.rds"))
  }
})
# } else {

try({
  m <- readRDS(here::here(paste0("data-generated/models/m-", spp, "-", ssid_string, name, ".rds")))
  if (max(m$gradients) > 0.01) {
    m <- run_extra_optimization(m, newton_loops = 1L, nlminb_loops = 0L)
    saveRDS(m, file = here::here("data-generated/models/m-", spp, "-", ssid_string, name, ".rds"))
  }
})
# }

try({
  m1
})
try({
  max(m1$gradients)
})
try({
  paste("Hessian positive and definite =", m1$sd_report$pdHess)
})
try({
  paste("Bad eigen =", m1$bad_eig)
})
try({
  tidy(m1, effects = "ran_pars", conf.int = TRUE)
})

try({
  m2
})
try({
  max(m2$gradients)
})
try({
  paste("Hessian positive and definite =", m2$sd_report$pdHess)
})

try({
  paste("Bad eigen =", m2$bad_eig)
})
try({
  tidy(m2, effects = "ran_pars", conf.int = TRUE)
})

try({
  m
})
try({
  max(m$gradients)
})
try({
  paste("Hessian positive and definite =", m$sd_report$pdHess)
})
try({
  paste("Bad eigen =", m$bad_eig)
})
try({
  tidy(m, effects = "ran_pars", conf.int = TRUE)
})
```

Check depths of positive sets
```{r}
hist(data$depth_m)
hist(positive_sets$depth_m)
depth_limit <- ifelse(
  max(positive_sets$depth_m, na.rm = T) > 500, max(positive_sets$depth_m, na.rm = T), max(positive_sets$depth_m, na.rm = T) + 100
)
```

Get simulated index
```{r}
dir.create(here::here("data-generated/indices"), showWarnings = FALSE)

nd <- nd_all %>%
  filter(year %in% unique(data$year)) %>%
  filter(depth < depth_limit)
if (type == "Synoptic trawl") {
  nd <- filter(nd, survey %in% unique(positive_sets$survey_abbrev))
} else {
  nd <- filter(nd, ssid %in% unique(positive_sets$survey_series_id))
}
nd <- na.omit(nd)
nd$year <- as.integer(nd$year)

samples <- data %>%
  count(year, survey_abbrev) %>%
  group_by(year) %>%
  mutate(freq = n / sum(n), total = sum(n)) %>%
  filter(n == max(n)) %>%
  select(year, dominant_surv = survey_abbrev, total, freq)

if (delta_model & exists("m1") & exists("m2")) {
  both_converged <- all(
    (max(m1$gradients) < 0.005), (max(m2$gradients) < 0.005),
    !m1$bad_eig, !m2$bad_eig,
    m1$sd_report$pdHess, m2$sd_report$pdHess # old way
    # m1$pos_def_hessian, m2$pos_def_hessian # new way
  )
  if (both_converged & update_index) {
    p1 <- predict(m1, newdata = nd, nsim = 200)
    p2 <- predict(m2, newdata = nd, nsim = 200)
    p <- log(plogis(p1) * exp(p2))

    i <- get_index_sims(p, area = nd$area)

    i <- i %>% mutate(
      species = species,
      type = type,
      region = region,
      surveys = paste(unique(positive_sets$survey_abbrev), collapse = ", "),
      ssids = paste(unique(positive_sets$survey_series_id), collapse = ", "),
      ssid_string = ssid_string,
      model = "delta-gamma",
      max_grad = max(max(m1$gradients), max(m2$gradients))
    )
    i <- left_join(i, samples)
    saveRDS(i, here::here(paste0("data-generated/indices/i-", spp, "-", ssid_string, name, "-delta.rds")))
  }
} else {
  if (exists("m")) {
    if (max(m$gradients) < 0.1 & !m$bad_eig & m$sd_report$pdHess & update_index) {
      p <- predict(m, newdata = nd, nsim = 200)

      i <- get_index_sims(p, area = nd$area)
      i <- i %>% mutate(
        species = species,
        type = type,
        region = region,
        surveys = paste(unique(positive_sets$survey_abbrev), collapse = ", "),
        ssids = paste(unique(positive_sets$survey_series_id), collapse = ", "),
        ssid_string = ssid_string,
        model = "Tweedie",
        max_grad = max(m$gradients)
      )
      i <- left_join(i, samples)
      saveRDS(i, here::here(paste0("data-generated/indices/i-", spp, "-", ssid_string, name, ".rds")))
    }
  }
}
```

```{r}
dir.create(here::here("figs"), showWarnings = FALSE)
if (delta_model) {
  try({
    i <- readRDS(here::here(paste0("data-generated/indices/i-", spp, "-", ssid_string, name, "-delta.rds")))
  })
} else {
  try({
    i <- readRDS(here::here(paste0("data-generated/indices/i-", spp, "-", ssid_string, name, ".rds")))
  })
}

if (region %in% c("North (PMFC 5DE)", "WCHG only")) {
  y_threshold <- max(i$upr)
} else {
  y_threshold <- 5
}

if (exists("i")) {
  g <- ggplot(i, aes(year, est / 1000)) +
    geom_line() +
    geom_ribbon(aes(ymin = lwr / 1000, ymax = upr / 1000), alpha = 0.4) +
    coord_cartesian(ylim = c(0, ifelse(
      max(i$upr) < y_threshold * max(i$est), max(i$upr) / 1000, max(i$est) * 3 / 1000
    ))) +
    ylab("Biomass (tonnes)") +
    ggtitle(paste(species), subtitle = paste0(region, " (", surv_string, ")"))
  ggsave(paste0("figs/", spp, "-", ssid_string, name, ".png"), height = 4, width = 6)
  g
}
```
