stock_df <- tibble::tribble(
  ~stock, ~stock_clean, ~type,
  "arrowtooth_BC", "Arrowtooth Flounder BC", "Flatfish",
  "bocaccio_BC", "Bocaccio BC", "Rockfish",
  "canary_BC", "Canary BC", "Rockfish",
  "lingcod_4B", "Lingcod 4B", "Cod allies",
  "pacific_ocean_perch_3CD", "Pacific Ocean Perch 3CD", "Rockfish",
  "pacific_ocean_perch_5ABC", "Pacific Ocean Perch 5ABC", "Rockfish",
  "pacific_ocean_perch_5DE", "Pacific Ocean Perch 5DE", "Rockfish",
  "pcod_3CD", "Pacific Cod 3CD", "Cod",
  "pcod_5abcd", "Pacific Cod 5ABCD", "Cod",
  "petrale_sole_BC", "Petrale Sole BC", "Flatfish",
  "quillback_BC_Outside", "Quillback BC Outside", "Rockfish",
  "quillback_4B", "Quillback VI Inside", "Rockfish",
  "redstripe_rockfish_BC_North", "Redstripe Rockfish BC N", "Rockfish",
  "redstripe_rockfish_BC_South", "Redstripe Rockfish BC S", "Rockfish",
  "rocksole_5AB", "Rock Sole 5AB", "Flatfish",
  "rocksole_5CD", "Rock Sole 5CD", "Flatfish",
  "rougheye/blackspotted_BC_North", "Rougheye/Blacksp. BC N", "Rockfish",
  "rougheye/blackspotted_BC_South", "Rougheye/Blacksp. BC S", "Rockfish",
  "sablefish_BC", "Sablefish BC", "Cod allies",
  "shortspine_thornyhead_BC", "Shortspine Thornyhead BC", "Rockfish",
  "silvergray_BC", "Silvergray Rockfish BC", "Rockfish",
  "walleye_pollock_BC_North", "Walleye Pollock BC N", "Cod",
  "walleye_pollock_BC_South", "Walleye Pollock BC S", "Cod",
  "widow_rockfish_BC", "Widow Rockfish BC", "Rockfish",
  "yelloweye_4B", "Yelloweye Rockfish 4B", "Rockfish",
  "yellowtail_BC", "Yellowtail Rockfish BC", "Rockfish",
  "yellowmouth_BC", "Yellowmouth Rockfish BC", "Rockfish",
  "north_pacific_spiny_dogfish_BC", "Pacific Spiny Dogfish BC", "Sharks",
)
