stock_df <- tibble::tribble(
  ~stock, ~stock_clean,
  "arrowtooth_3CD", "Arrowtooth Flounder 3CD",
  "bocaccio_5ABCD", "Bocaccio 5ABCD",
  "lingcod_4B", "Lingcod 4B",
  "pacific_ocean_perch_3CD", "Pacific Ocean Perch 3CD",
  "pacific_ocean_perch_5ABC", "Pacific Ocean Perch 5ABC",
  "pacific_ocean_perch_5DE", "Pacific Ocean Perch 5DE",
  "pcod_3CD", "Pacific Cod 3CD",
  "pcod_5abcd", "Pacific Cod 5ABCD",
  "quillback_BC_Outside", "Quillback BC Outside",
  "quillback_WCVI_Inside", "Quillback VI Inside",
  "redstripe_rockfish_BC_North", "Redstripe Rockfish BC N",
  "redstripe_rockfish_BC_South", "Redstripe Rockfish BC S",
  "rocksole_5AB", "Rocksole 5AB",
  "rocksole_5CD", "Rocksole 5CD",
  "rougheye/blackspotted_BC_North", "Rougheye/Blacksp. BC N",
  "rougheye/blackspotted_BC_South", "Rougheye/Blacksp. BC S",
  "sablefish_BC", "Sablefish BC",
  "shortspine_thornyhead_BC", "Shortspine Thornyhead BC",
  "silvergray_BC", "Silvergray Rockfish BC",
  "walleye_pollock_BC_North", "Walleye Pollock BC N",
  "walleye_pollock_BC_South", "Walleye Pollock BC S",
  "widow_rockfish_BC", "Widow Rockfish BC",
  "yelloweye_4B", "Yelloweye Rockfish 4B",
  "yellowtail_BC", "Yellowtail Rockfish BC"
)
