stock_df <- tibble::tribble(
  ~stock, ~stock_clean, ~type, ~species, ~region,
  "arrowtooth_BC", "Arrowtooth Flounder BC", "Flatfish", "Arrowtooth Flounder", "Coast-wide trawl surveys",
  "bocaccio_BC", "Bocaccio BC", "Rockfish", "Bocaccio", "Coast-wide trawl surveys",
  "lingcod_4B", "Lingcod 4B", "Cod allies", "Lingcod", "HBLL inside surveys",
  "dogfish_BC", "North Pacific Spiny Dogfish BC", "Sharks", "North Pacific Spiny Dogfish", "Coast-wide trawl surveys",
  "dogfish_BC", "North Pacific Spiny Dogfish BC", "Sharks", "North Pacific Spiny Dogfish", "HBLL outside surveys",
  "dogfish_4B", "North Pacific Spiny Dogfish 4B", "Sharks", "North Pacific Spiny Dogfish", "HBLL inside surveys",
  "pacific_ocean_perch_3CD", "Pacific Ocean Perch 3CD", "Rockfish", "Pacific Ocean Perch", "WCVI only",
  "pacific_ocean_perch_5ABC", "Pacific Ocean Perch 5ABC", "Rockfish", "Pacific Ocean Perch", "South 5 only (PMFC 5ABC)",
  "pacific_ocean_perch_5DE", "Pacific Ocean Perch 5DE", "Rockfish", "Pacific Ocean Perch", "North (PMFC 5DE)",
  "pcod_3CD", "Pacific Cod 3CD", "Cod", "Pacific Cod", "WCVI only",
  "pcod_5abcd", "Pacific Cod 5ABCD", "Cod", "Pacific Cod", "Both odd year trawl surveys",
  "quillback_BC_Outside", "Quillback BC Outside", "Rockfish", "Quillback Rockfish", "HBLL outside surveys",
  "quillback_WCVI_Inside", "Quillback VI Inside", "Rockfish", "Quillback Rockfish", "HBLL inside surveys",
  "redstripe_rockfish_BC_North", "Redstripe Rockfish BC N", "Rockfish", "Redstripe Rockfish", "North (PMFC 5DE)",
  "redstripe_rockfish_BC_South", "Redstripe Rockfish BC S", "Rockfish", "Redstripe Rockfish", "South (PMFC 3CD5ABC)",
  "rocksole_5AB", "Rocksole 5AB", "Flatfish", "Southern Rock Sole", "QCS only",
  "rocksole_5CD", "Rocksole 5CD", "Flatfish", "Southern Rock Sole", "HS only",
  "rougheye/blackspotted_BC_North", "Rougheye/Blacksp. BC N", "Rockfish", "Rougheye/Blackspotted Rockfish Complex", "North (PMFC 5DE)",
  "rougheye/blackspotted_BC_South", "Rougheye/Blacksp. BC S", "Rockfish", "Rougheye/Blackspotted Rockfish Complex", "South (PMFC 3CD5ABC)",
  "sablefish_BC", "Sablefish BC", "Cod allies", "Sablefish", "Coast-wide trawl surveys",
  "sablefish_BC", "Sablefish BC", "Cod allies", "Sablefish", "HBLL outside surveys",
  "shortspine_thornyhead_BC", "Shortspine Thornyhead BC", "Rockfish", "Shortspine Thornyhead", "Coast-wide trawl surveys",
  "silvergray_BC", "Silvergray Rockfish BC", "Rockfish","Silvergray Rockfish", "Coast-wide trawl surveys",
  "walleye_pollock_BC_North", "Walleye Pollock BC N", "Cod", "Walleye Pollock", "HS & WCHG",
  "walleye_pollock_BC_South", "Walleye Pollock BC S", "Cod", "Walleye Pollock", "QCS & WCVI",
  "widow_rockfish_BC", "Widow Rockfish BC", "Rockfish", "Widow Rockfish", "Coast-wide trawl surveys",
  "yelloweye_BC", "Yelloweye Rockfish BC Outside", "Rockfish", "Yelloweye Rockfish", "HBLL outside surveys",
  "yelloweye_4B", "Yelloweye Rockfish 4B", "Rockfish", "Yelloweye Rockfish", "HBLL inside surveys",
  "yellowmouth_BC", "Yellowmouth Rockfish BC", "Rockfish", "Yellowmouth Rockfish", "Coast-wide trawl surveys",
  "yellowtail_BC", "Yellowtail Rockfish BC", "Rockfish", "Yellowtail Rockfish", "Coast-wide trawl surveys"
)
